# Generated by Django 2.1.5 on 2025-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20181209_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
    ]