# Generated by Django 2.1.4 on 2021-01-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер работы')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('doctor', models.CharField(max_length=255, verbose_name='Доктор')),
                ('patient', models.CharField(max_length=255, verbose_name='Пациент')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Оплачено')),
                ('entered_date', models.DateField(verbose_name='Дата поступления')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_paid', models.BooleanField(blank=True, default=False, verbose_name='Оплачено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.Product', verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
    ]
