# Generated by Django 2.1.4 on 2018-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181208_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
    ]
