# Generated by Django 2.1.4 on 2018-12-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20181217_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
    ]
